<?php 
/**
 * Mageplaza_BetterBlog extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Mageplaza
 * @package        Mageplaza_BetterBlog
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Category Post list template
 *
 * @category    Mageplaza
 * @package     Mageplaza_BetterBlog
 * @author      Sam
 */
?>
<?php $_posts = $this->getPosts(); ?>
<?php if ($_posts->getSize() > 0) :?>
    <div class="post-list-container">
        <?php foreach ($_posts as $_post) : ?>
            <div class="post-list-item">
                <div class="post-image">
                    <?php if ($_post->getImage()) : ?>
                        <a href="<?php echo $_post->getPostUrl(); ?>" title="<?php echo $_post->getPostTitle(); ?>">
                            <img class="zoom" src="<?php echo Mage::helper('mageplaza_betterblog/post_image')->init($_post, 'image'); ?>" alt="<?php echo $this->escapeHtml($_post->getPostTitle()); ?>"/>
                        </a>
                    <?php endif; ?>
                </div>

                <div class="inner">
                    <div class="mc-post-info">
                        <?php echo $this->__('Posted on'); ?> <?php echo Mage::helper('core')->formatDate($_post->getCreatedAt(), 'medium', false) ?> 
                        <?php if(Mage::helper('mageplaza_betterblog')->canShowCommentCount()) echo '| '. Mage::helper('mageplaza_betterblog')->formatCommentCount($_post->getCommentCount()); ?>
                    </div>

                   
                    <a href="<?php echo $_post->getPostUrl() ?>">
                        <?php echo $_post->getPostTitle(); ?>
                    </a>

                    <div class="post-short-description">
                        <p><?php echo $_post->getPostExcerpt(); ?><?php echo $this->__('...'); ?></p>
                    </div>

                    <div class="mc-clearfix"></div>


                    <div class="mc-post-meta-info mc-alignright">
                        <div class="actions">
                            <a class="mc-read-more" href="<?php echo $_post->getPostUrl(); ?>" title="<?php echo $this->__('Read More'); ?>">
                                <?php echo $this->__('Read More'); ?>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <?php else : ?>
        <div class="post-list-container">
            <?php echo Mage::helper('mageplaza_betterblog')->__('There are no posts at this moment. '); ?>
            <a href="<?php echo Mage::getBaseUrl();?>/blog"> Back to Blog</a>
        </div>
    <?php endif; ?>
